### ISSUE TITLE
Wrong status. isitww3yet.com says "no"

### ISSUE THREAD

**Issue by raphaeljolivet** [Accurate0/isitww3yet.com#1]
Your website [isitww3yet.com](isitww3yet.com) seems broken.
It indicates "no", while the war on Ukraine already started :
https://en.wikipedia.org/wiki/2021%E2%80%932022_Russo-Ukrainian_crisis#Invasion

Please update both the API and website accordingly.

😬

**Comment by Accurate0** [comment]
thanks, this is fixed now
